# Generated by Django 4.2.2 on 2023-06-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
