# Generated by Django 4.2.2 on 2023-06-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryShop', '0004_basketgoods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketgoods',
            name='user',
        ),
        migrations.AlterField(
            model_name='basketgoods',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
