# Generated by Django 4.2.2 on 2023-06-08 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryShop', '0005_remove_basketgoods_user_alter_basketgoods_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketgoods',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deliveryShop.shop'),
        ),
        migrations.AlterField(
            model_name='basketgoods',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_goods', to='deliveryShop.basket'),
        ),
        migrations.AlterUniqueTogether(
            name='basketgoods',
            unique_together={('basket', 'goods')},
        ),
    ]
